custom_strings.h File Reference
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include hash.h
Functions
int cus_puts (const char *str)
Puts string str to standart output. \0 => \n.
char * cus_strchr (const char *str, const int symbol)
Finds first positions of symbol in str and returns it's pointer.
size_t cus_strlen (const char *str)
Counts str len.
char * cus_strcpy (char *dest, const char *src)
Copies src to target.
char * cus_strncpy (char *dest, const char *src, size_t cnt)
Copies max cnt symbols from src to target.
char * cus_strcat (char *dest, const char *src)
Concatenates src to dest.
char * cus_strncat (char *dest, const char *src, size_t cnt)
Concatenates max cnt symbols from src to dest.
char * cus_fgets (char *str, int cnt, FILE *stream)
Reads max cnt-1 symbols from stream to str.
char * cus_strdup (const char *str)
Allocates memory for str, copies it and returns pointer.
ssize_t cus_getline (char **str, size_t *cnt, FILE *stream)
Gets line from stream.
bool geom_realloc (void **mem, const size_t elem_size, size_t *size)
Geometric realloc.
char * cus_strstr_simple (const char *str, const char *substr)
Finds first inclusion of substr in str and returns its pointer Simple algorithm O(n * m)
char * cus_strstr_kmp (const char *str, const char *substr)
Finds first inclusion of substr in str and returns its pointer Knutt Morris Pratt algorithm O(n + m)
const char * ptr_emulate (size_t i, const char *prefix, const char *str, size_t prefix_len, const char *empty)
Returns pointer by index for emulation of concatination of prefix + empty (1 char) + str.
char * cus_strstr_bm (const char *str, const char *substr)
Finds first inclusion of substr in str and returns its pointer Boyer Moore algorithm. O(n / m) - O(n * m)
char * cus_strstr_hash (const char *str, const char *substr)
Finds first inclusion of substr in str and returns its pointer Reversed polinomial hash algorithm O(n + m)
Function Documentation
cus_fgets()
char * cus_fgets (char * str, int cnt, FILE * stream)
Reads max cnt-1 symbols from stream to str.
Parameters
str
cnt
stream
Returns
char* if succeed str, else nullptr
Definition at line 84 of file custom_strings.cpp.
                                                  {
    assert(str);
    assert(stream);
    size_t i = 0;
    int c = '\0';
    for (i = 0; i < (size_t)cnt - 1 && c != '\n'; i++) {
        c = getc(stream);
        if (c == EOF)
            return nullptr;
        str[i] = (char)c;
    }
    str[i] = '\0';
    return str;
}
cus_getline()
ssize_t cus_getline (char ** str, size_t * cnt, FILE * stream)
Gets line from stream.
Parameters
str
cnt
stream
Returns
ssize_t Number of characters were read. -1 in case of error
Definition at line 113 of file custom_strings.cpp.
                                                           {
    assert(str);
    assert(*str || *cnt); // check for *cnt > 0 if *str != nullptr
    assert(stream);
    static const size_t BEGIN_ALLOC_SIZE = 256;
    if (*str == nullptr) {
        *cnt = BEGIN_ALLOC_SIZE;
        *str = (char*)malloc(*cnt * sizeof(char));
        if (*str == nullptr)
            return -1;
    }
    size_t i = 0;
    int c = '\0';
    for (i = 0; c != '\n'; i++) {
        if (i >= *cnt - 1)
            if (!geom_realloc((void**)str, sizeof(char), cnt))
                return -1;
        c = fgetc(stream);
        if (c == EOF)
            return -1;
        *str[i] = (char)c;
    }
    *str[i] = '\0';
    return i;
}
References geom_realloc().
cus_puts()
int cus_puts (const char * str)
Puts string str to standart output. \0 => \n.
Parameters
str string
Returns
int if succeed - '
' else EOF
Definition at line 3 of file custom_strings.cpp.
                              {
    assert(str);
    for (size_t i = 0; str[i] != '\0'; i++) {
        if (putc(str[i], stdout) == EOF)
            return EOF;
    }
    return putc('\n', stdout);
}
cus_strcat()
char * cus_strcat (char * dest, const char * src)
Concatenates src to dest.
Parameters
dest
src
Returns
char* dest
Definition at line 60 of file custom_strings.cpp.
                                              {
    assert(dest);
    assert(src);
    char* dest_cat = cus_strchr(dest, '\0');
    assert(dest_cat);
    cus_strcpy(dest_cat, src);
    return dest;
}
References cus_strchr(), and cus_strcpy().
Referenced by test_cus_strcat().
cus_strchr()
char * cus_strchr (const char * str, const int symbol)
Finds first positions of symbol in str and returns it's pointer.
Parameters
str
symbol
Returns
char* First symbol found in str pointer. If not found, returns nullptr
Definition at line 13 of file custom_strings.cpp.
                                                    {
    assert(str);
    size_t i = 0;
    do {
        if (str[i] == symbol)
            return const_cast<char*>(str) + i;
    } while (str[i++] != '\0');
    return nullptr;
}
Referenced by cus_strcat(), cus_strncat(), and test_cus_strchr().
cus_strcpy()
char * cus_strcpy (char * dest, const char * src)
Copies src to target.
Parameters
dest
src
Returns
char* dest
Definition at line 35 of file custom_strings.cpp.
                                              {
    assert(dest);
    assert(src);
    size_t i = 0;
    do {
        dest[i] = src[i];
    } while (src[i++] != '\0');
    return dest;
}
Referenced by cus_strcat(), cus_strdup(), and test_cus_strcpy().
cus_strdup()
char * cus_strdup (const char * str)
Allocates memory for str, copies it and returns pointer.
Parameters
str
Returns
char*
Definition at line 102 of file custom_strings.cpp.
                                  {
    assert(str);
    char* output = (char*)malloc((cus_strlen(str) + 1) * sizeof(char));
    if (output == nullptr)
        return nullptr;
    cus_strcpy(output, str);
    return output;
}
References cus_strcpy(), and cus_strlen().
cus_strlen()
size_t cus_strlen (const char * str)
Counts str len.
Parameters
str
Returns
size_t
Definition at line 26 of file custom_strings.cpp.
                                   {
    assert(str);
    for (size_t i = 0;; i++) {
        if (str[i] == '\0')
            return i;
    }
}
Referenced by cus_strdup(), cus_strstr_bm(), cus_strstr_hash(), cus_strstr_kmp(), and test_cus_strlen().
cus_strncat()
char * cus_strncat (char * dest, const char * src, size_t cnt)
Concatenates max cnt symbols from src to dest.
Parameters
dest
src
cnt
Returns
char* dest
Definition at line 72 of file custom_strings.cpp.
                                                           {
    assert(dest);
    assert(src);
    char* dest_cat = cus_strchr(dest, '\0');
    assert(dest_cat);
    cus_strncpy(dest_cat, src, cnt);
    return dest;
}
References cus_strchr(), and cus_strncpy().
Referenced by test_cus_strncat().
cus_strncpy()
char * cus_strncpy (char * dest, const char * src, size_t cnt)
Copies max cnt symbols from src to target.
Parameters
dest
src
cnt
Returns
char*
Definition at line 47 of file custom_strings.cpp.
                                                           {
    assert(dest);
    assert(src);
    size_t i = 0;
    for (i = 0; src[i] != '\0' && i < cnt; i++) {
        dest[i] = src[i];
    }
    dest[i] = '\0';
    return dest;
}
Referenced by cus_strncat(), and test_cus_strncpy().
cus_strstr_bm()
char * cus_strstr_bm (const char * str, const char * substr)
Finds first inclusion of substr in str and returns its pointer Boyer Moore algorithm. O(n / m) - O(n * m)
Parameters
str
substr
Returns
char*
Definition at line 233 of file custom_strings.cpp.
                                                         {
    assert(str);
    assert(substr);
    size_t preproc[256] = {};
    size_t substr_len = cus_strlen(substr);
    for (size_t i = 0; i < 256; i++)
        preproc[i] = substr_len;
    for (size_t i = 0; i < substr_len; i++) {
        preproc[(size_t)substr[i]] = __min(preproc[(size_t)substr[i]], substr_len - i - 1);
    }
    size_t str_len = cus_strlen(str);
    for (size_t i = substr_len - 1; i < str_len; i++) {
        while (i < str_len && preproc[(size_t)str[i]] != 0)
            i += preproc[(size_t)str[i]];
        if (i >= str_len) break;
        if (strncmp(substr, str + i - substr_len + 1, substr_len) == 0)
            return const_cast<char*>(str) + i - substr_len + 1;
    }
    return nullptr;
}
References cus_strlen().
Referenced by test_all().
cus_strstr_hash()
char * cus_strstr_hash (const char * str, const char * substr)
Finds first inclusion of substr in str and returns its pointer Reversed polinomial hash algorithm O(n + m)
Parameters
str
substr
Returns
char*
Definition at line 264 of file custom_strings.cpp.
                                                           {
    assert(str);
    assert(substr);
    size_t substr_len = cus_strlen(substr);
    Hash substr_hash = hash_create(substr, substr_len);
    Hash str_hash = hash_create(str, substr_len);
    for (size_t i = 0; str[i + substr_len - 1] != '\0' ; i++) {
        if (str_hash.hash == substr_hash.hash) {
            if (strncmp(str + i, substr, substr_len) == 0) {
                return const_cast<char*>(str) + i;
            }
        }
        hash_move(&str_hash, str[i], str[i + substr_len]);
    }
    return nullptr;
}
References cus_strlen(), Hash::hash, hash_create(), and hash_move().
Referenced by test_all().
cus_strstr_kmp()
char * cus_strstr_kmp (const char * str, const char * substr)
Finds first inclusion of substr in str and returns its pointer Knutt Morris Pratt algorithm O(n + m)
Parameters
str
substr
Returns
char*
< prefix function
REVIEW is static is justified. Memory leak?
< initial alloc
< if pref_len is too small
Definition at line 184 of file custom_strings.cpp.
                                                          {
    assert(str);
    assert(substr);
    size_t substr_len = cus_strlen(substr);
    size_t str_len = cus_strlen(str);
    static size_t* pref = nullptr;
    static size_t pref_len = 0;
    if (pref == nullptr) {
        pref_len = str_len + substr_len + 1;
        pref = (size_t*)calloc(pref_len, sizeof(size_t));
    } else if (pref_len < str_len + substr_len + 1) {
        pref_len = str_len + substr_len + 1;
        pref = (size_t*)realloc(pref, pref_len * sizeof(size_t));
    }
    if (pref == nullptr)
        return nullptr;
    pref[0] = 0;
    for (size_t i = 1; i < pref_len; i++) {
        size_t j = pref[i - 1];
        while ((j > 0) && (*ptr_emulate(i, substr, str, substr_len, "") != *ptr_emulate(j, substr, str, substr_len, "")))
            j = pref[j - 1];
        if (*ptr_emulate(i, substr, str, substr_len, "") == *ptr_emulate(j, substr, str, substr_len, ""))
            j++;
        pref[i] = j;
        if (j == substr_len) {
            return const_cast<char*>(str) + i - 2 * substr_len;
        }
    }
    return nullptr;
}
References cus_strlen(), and ptr_emulate().
Referenced by test_all().
cus_strstr_simple()
char * cus_strstr_simple (const char * str, const char * substr)
Finds first inclusion of substr in str and returns its pointer Simple algorithm O(n * m)
Parameters
str
substr
Returns
char*
Definition at line 153 of file custom_strings.cpp.
                                                             {
    assert(str);
    assert(substr);
    for (size_t i = 0; str[i] != '\0'; i++) {
        bool is_equal = true;
        char first_c = str[i];
        size_t same_len = 0;
        for (size_t j = 0; substr[j] != '\0'; j++) {
            if (str[i + j] != substr[j]) {
                is_equal = false;
                i += j - same_len;
                break;
            }
            if (str[i + j] == first_c)
                same_len++;
            else if (first_c != '\0') {
                same_len++;
                first_c = '\0';
            }
        }
        if (is_equal)
            return const_cast<char*>(str) + i;
    }
    return nullptr;
}
Referenced by test_all().
geom_realloc()
bool geom_realloc (void ** mem, const size_t elem_size, size_t * size)
Geometric realloc.
Parameters
mem array pointer
elem_size type size
size array len
Returns
true if succeed
false if realloc failed
Definition at line 145 of file custom_strings.cpp.
                                                              {
    *size *= 2;
    *mem = realloc(*mem, (*size) * elem_size);
    if (*mem == nullptr)
        return false;
    return true;
}
Referenced by cus_getline().
ptr_emulate()
const char * ptr_emulate (size_t i, const char * prefix, const char * str, size_t prefix_len, const char * empty)
Returns pointer by index for emulation of concatination of prefix + empty (1 char) + str.
Parameters
i
prefix
str
prefix_len
empty
Returns
const char*
Definition at line 227 of file custom_strings.cpp.
                                                                                                             {
    if (i == prefix_len) return empty;
    else if(i < prefix_len) return prefix + i;
    else return str + i - prefix_len - 1;
}
Referenced by cus_strstr_kmp().