test/test.cpp File Reference
#include test.h
Functions
void test_all ()
Tests all.
TestResult test_cus_strchr (const char *str, const int symbol)
Tests cus_strchr()
TestResult test_cus_strlen (const char *str)
Tests cus_strlen()
TestResult test_cus_strcpy (const char *src)
Tests cus_strcpy.
TestResult test_cus_strncpy (const char *src, size_t cnt)
Tests cus_strncpy.
TestResult test_cus_strcat (const char *src)
Tests cus_strcat()
TestResult test_cus_strncat (const char *src, size_t cnt)
Tests cus_strncat.
TestResult test_cus_strstr (const char *str, const char *substr, char *(*test_func)(const char *str, const char *substr))
Tests cus_strstr.
void bruteforce_char (char *str1, size_t depth1, char *str2, size_t depth2, unsigned int *test_num, unsigned int *test_success_num, char *(*test_func)(const char *str, const char *substr))
Recursively generates 2 strings.
Function Documentation
bruteforce_char()
void bruteforce_char (char * str1, size_t depth1, char * str2, size_t depth2, unsigned int * test_num, unsigned int * test_success_num, char *(*)(const char *str, const char *substr) test_func)
Recursively generates 2 strings.
Parameters
str1 pointer to first string buffer
depth1 length of str1
str2 pointer to second string buffer
depth2 length of str2
test_num pointer
test_success_num pointer
test_func pointer to the funstion that is being tested
Definition at line 307 of file test.cpp.
                                                                              {
    if (depth1 == 0 && depth2 == 0) {
        (*test_num)++;
        if (test_cus_strstr(str1, str2, test_func) == TestResult::PASSED) {
            (*test_success_num)++;
        } else {
            printf(CONSOLE_RED("Test %u failed.\n"), *test_num);
        }
        return;
    }
    else if (depth1 == 0) {
        depth2--;
        for (size_t i = 0; i < 3; i++) {
            str2[depth2] = 'a' + (char)i;
            bruteforce_char(str1, depth1, str2, depth2, test_num, test_success_num, test_func);
        }
        return;
    }
    depth1--;
    for (size_t i = 0; i < 3; i++) {
        str1[depth1] = 'a' + (char)i;
        bruteforce_char(str1, depth1, str2, depth2, test_num, test_success_num, test_func);
    }
}
References bruteforce_char(), CONSOLE_RED, PASSED, and test_cus_strstr().
Referenced by bruteforce_char(), and test_all().
test_all()
void test_all ()
Tests all.
Definition at line 3 of file test.cpp.
                {
    unsigned int test_num = 0;
    unsigned int test_success_num = 0;
    // test_cus_strchr
    printf("Testing cus_strchr\n");
    test_num = 0;
    test_success_num = 0;
    for (int i = 0; i < 9; i++) {
        test_num++;
        if (test_cus_strchr("12345678", '0' + i) == TestResult::PASSED)
            test_success_num++;
        else
            printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    }
    test_num++;
    if (test_cus_strchr("12345678", '\0') == TestResult::PASSED)
        test_success_num++;
    else
        printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    print_section_test_results(test_num, test_success_num);
    // test_cus_strlen
    printf("Testing cus_strlen\n");
    test_num = 0;
    test_success_num = 0;
    const char* buf = "123456789";
    for (int i = 0; i < 10; i++) {
        test_num++;
        if (test_cus_strlen(buf + i) == TestResult::PASSED)
            test_success_num++;
        else
            printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    }
    print_section_test_results(test_num, test_success_num);
    // test_cus_strcpy
    printf("Testing cus_strcpy\n");
    test_num = 0;
    test_success_num = 0;
    buf = "123456789";
    for (int i = 0; i < 10; i++) {
        test_num++;
        if (test_cus_strcpy(buf + i) == TestResult::PASSED)
            test_success_num++;
        else
            printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    }
    print_section_test_results(test_num, test_success_num);
    // test_cus_strncpy
    printf("Testing cus_strncpy\n");
    test_num = 0;
    test_success_num = 0;
    for (int i = 0; i < 10; i++) {
        test_num++;
        if (test_cus_strncpy("12345678", i) == TestResult::PASSED)
            test_success_num++;
        else
            printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    }
    print_section_test_results(test_num, test_success_num);
    // test_cus_strcat
    printf("Testing cus_strcat\n");
    test_num = 0;
    test_success_num = 0;
    buf = "123456789";
    for (int i = 0; i < 10; i++) {
        test_num++;
        if (test_cus_strcat(buf + i) == TestResult::PASSED)
            test_success_num++;
        else
            printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    }
    print_section_test_results(test_num, test_success_num);
    // test_cus_strncat
    printf("Testing cus_strncat\n");
    test_num = 0;
    test_success_num = 0;
    for (int i = 0; i < 10; i++) {
        test_num++;
        if (test_cus_strncat("12345678", i) == TestResult::PASSED)
            test_success_num++;
        else
            printf(CONSOLE_RED("Test %u failed.\n"), test_num);
    }
    print_section_test_results(test_num, test_success_num);
    // test_cus_strstr
    char str1[11];
    str1[10] = '\0';
    char str2[5];
    str2[4] = '\0';
    // test_cus_strstr_simple
    printf("Testing cus_strstr_simple\n");
    test_num = 0;
    test_success_num = 0;
    bruteforce_char(str1, 10, str2, 4, &test_num, &test_success_num, &cus_strstr_simple);
    print_section_test_results(test_num, test_success_num);
    // test_cus_strstr_bm
    printf("Testing cus_strstr_bm\n");
    test_num = 0;
    test_success_num = 0;
    bruteforce_char(str1, 10, str2, 4, &test_num, &test_success_num, &cus_strstr_bm);
    print_section_test_results(test_num, test_success_num);
    // test_cus_strstr_hash
    printf("Testing cus_strstr_hash\n");
    test_num = 0;
    test_success_num = 0;
    bruteforce_char(str1, 10, str2, 4, &test_num, &test_success_num, &cus_strstr_hash);
    print_section_test_results(test_num, test_success_num);
    // test_cus_strstr_kmp
    printf("Testing cus_strstr_kmp\n");
    test_num = 0;
    test_success_num = 0;
    bruteforce_char(str1, 10, str2, 4, &test_num, &test_success_num, &cus_strstr_kmp);
    print_section_test_results(test_num, test_success_num);
}
References bruteforce_char(), CONSOLE_RED, cus_strstr_bm(), cus_strstr_hash(), cus_strstr_kmp(), cus_strstr_simple(), PASSED, print_section_test_results(), test_cus_strcat(), test_cus_strchr(), test_cus_strcpy(), test_cus_strlen(), test_cus_strncat(), and test_cus_strncpy().
Referenced by main().
test_cus_strcat()
TestResult test_cus_strcat (const char * src)
Tests cus_strcat()
Parameters
src
Returns
TestResult
Definition at line 230 of file test.cpp.
                                            {
    char buf[1000] = "123";
    char buf_ref[1000] = "123";
    char* result_ref = strcat(buf_ref, src);
    char* result = cus_strcat(buf, src);
    if (result_ref == nullptr || result == nullptr) {
        if (result == result_ref)
            return TestResult::PASSED;
        else {
            printf("Must be\n"
                   "%s\n"
                   "instead of\n"
                    "%s\n", result_ref, result);
            return TestResult::FAILED;
        }
    }
    if (strcmp(result, result_ref) != 0) {
        printf("Must be\n"
               "%s\n"
               "instead of\n"
               "%s\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References cus_strcat(), FAILED, and PASSED.
Referenced by test_all().
test_cus_strchr()
TestResult test_cus_strchr (const char * str, const int symbol)
Tests cus_strchr()
Parameters
str
symbol
ptr_ref
Returns
TestResult
Definition at line 130 of file test.cpp.
                                                              {
    assert(str);
    char* result = cus_strchr(str, symbol);
    char* result_ref = strchr(str, symbol);
    if (result_ref == nullptr || result == nullptr) {
        if (result == result_ref)
            return TestResult::PASSED;
        else {
            printf("Must be\n"
                   "%s\n"
                   "instead of\n"
                    "%s\n", result_ref, result);
            return TestResult::FAILED;
        }
    }
    if (strcmp(result, result_ref) != 0) {
        printf("Must be\n"
               "%s\n"
               "instead of\n"
               "%s\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References cus_strchr(), FAILED, and PASSED.
Referenced by test_all().
test_cus_strcpy()
TestResult test_cus_strcpy (const char * src)
Tests cus_strcpy.
Parameters
src
Returns
TestResult
Definition at line 172 of file test.cpp.
                                            {
    char buf[1000] = "";
    char buf_ref[1000] = "";
    char* result_ref = strcpy(buf_ref, src);
    char* result = cus_strcpy(buf, src);
    if (result_ref == nullptr || result == nullptr) {
        if (result == result_ref)
            return TestResult::PASSED;
        else {
            printf("Must be\n"
                   "%s\n"
                   "instead of\n"
                    "%s\n", result_ref, result);
            return TestResult::FAILED;
        }
    }
    if (strcmp(result, result_ref) != 0) {
        printf("Must be\n"
               "%s\n"
               "instead of\n"
               "%s\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References cus_strcpy(), FAILED, and PASSED.
Referenced by test_all().
test_cus_strlen()
TestResult test_cus_strlen (const char * str)
Tests cus_strlen()
Parameters
str
Returns
TestResult
Definition at line 159 of file test.cpp.
                                            {
    assert(str);
    size_t result_ref = strlen(str);
    size_t result = cus_strlen(str);
    if (result != result_ref) {
        printf("Must be %lld instead of %lld\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References cus_strlen(), FAILED, and PASSED.
Referenced by test_all().
test_cus_strncat()
TestResult test_cus_strncat (const char * src, size_t cnt)
Tests cus_strncat.
Parameters
src
cnt
Returns
TestResult
Definition at line 259 of file test.cpp.
                                                         {
    char buf[1000] = "123";
    char buf_ref[1000] = "123";
    char* result_ref = strncat(buf_ref, src, cnt);
    char* result = cus_strncat(buf, src, cnt);
    if (result_ref == nullptr || result == nullptr) {
        if (result == result_ref)
            return TestResult::PASSED;
        else {
            printf("Must be\n"
                   "%s\n"
                   "instead of\n"
                    "%s\n", result_ref, result);
            return TestResult::FAILED;
        }
    }
    if (strcmp(result, result_ref) != 0) {
        printf("Must be\n"
               "%s\n"
               "instead of\n"
               "%s\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References cus_strncat(), FAILED, and PASSED.
Referenced by test_all().
test_cus_strncpy()
TestResult test_cus_strncpy (const char * src, size_t cnt)
Tests cus_strncpy.
Parameters
src
cnt
Returns
TestResult
Definition at line 201 of file test.cpp.
                                                         {
    char buf[1000] = "";
    char buf_ref[1000] = "";
    char* result_ref = strncpy(buf_ref, src, cnt);
    char* result = cus_strncpy(buf, src, cnt);
    if (result_ref == nullptr || result == nullptr) {
        if (result == result_ref)
            return TestResult::PASSED;
        else {
            printf("Must be\n"
                   "%s\n"
                   "instead of\n"
                    "%s\n", result_ref, result);
            return TestResult::FAILED;
        }
    }
    if (strcmp(result, result_ref) != 0) {
        printf("Must be\n"
               "%s\n"
               "instead of\n"
               "%s\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References cus_strncpy(), FAILED, and PASSED.
Referenced by test_all().
test_cus_strstr()
TestResult test_cus_strstr (const char * str, const char * substr, char *(*)(const char *str, const char *substr) test_func)
Tests cus_strstr.
Parameters
str
substr
test_func pointer to the funstion that is being tested
Returns
TestResult
Definition at line 288 of file test.cpp.
                                                                                                                         {
    char* result_ref = strstr(str, substr);
    char* result = (*test_func)(str, substr);
    if (result == result_ref)
        return TestResult::PASSED;
    else {
        printf("str: %s\n", str);
        printf("substr: %s\n", substr);
        printf("Must be\n"
                "%s\n"
                "instead of\n"
                "%s\n", result_ref, result);
        return TestResult::FAILED;
    }
    return TestResult::PASSED;
}
References FAILED, and PASSED.
Referenced by bruteforce_char().